#undef ABSORB_NUTRITION_BARRIER
#undef NUTRITION_PER_DAMAGE
#undef NUTRITION_PER_KILL
#undef VORE_SOUND_VOLUME
#undef PREYLOOP_VOLUME
#undef TRAIT_SOURCE_VORE

#undef DIGEST_MODE_DRAIN
#undef DIGEST_MODE_HEAL
