/obj/item/fugu_gland/interact_with_atom(mob/living/interacting_with, mob/living/user, list/modifiers)
	. = ..()
	if(. & ITEM_INTERACT_SUCCESS)
		var/old_size = get_size(interacting_with)
		interacting_with.update_size(old_size * 2)
		if(!ishuman(interacting_with))
			interacting_with.update_transform(get_size(interacting_with) / old_size)
