/obj/machinery/vending/wardrobe/sec_wardrobe
	zzplurt_product_categories = list(
		list(
			"name" = "Red",
			"products" = list(
				/obj/item/storage/backpack/security = 6,
				/obj/item/storage/backpack/satchel/sec = 6,
				/obj/item/storage/backpack/messenger/sec = 6,
				/obj/item/storage/backpack/duffelbag/sec = 6,
				/obj/item/clothing/under/rank/security/splurt/officer = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/skirt = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/suit = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/casual = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/turtleneck = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/turtleneck/skirt = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/trousers = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/trousers/shorts = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/miniskirt = 6,
				/obj/item/clothing/under/rank/security/splurt/officer/battledress = 6,
				/obj/item/clothing/suit/armor/vest = 6,
				/obj/item/clothing/suit/armor/vest/alt = 6,
				/obj/item/clothing/suit/armor/vest/alt/sec = 6,
				/obj/item/clothing/suit/armor/vest/harness = 6,
				/obj/item/clothing/suit/toggle/jacket/sec = 6,
				/obj/item/clothing/suit/hooded/wintercoat/security = 6,
				/obj/item/clothing/suit/armor/vest/secjacket = 6,
				/obj/item/clothing/suit/armor/vest/secwintercoat = 6,
				/obj/item/clothing/suit/toggle/jacket/zubber/bomber/sec = 6,
				/obj/item/clothing/shoes/jackboots = 6,
				/obj/item/clothing/shoes/jackboots/knee = 6,
				/obj/item/clothing/shoes/jackboots/sec = 6,
				/obj/item/clothing/shoes/jackboots/gogo_boots = 6,
				/obj/item/clothing/head/helmet = 6,
				/obj/item/clothing/head/helmet/novisor = 6,
				/obj/item/clothing/head/helmet/sec/futuristic = 6,
				/obj/item/clothing/head/soft/sec = 6,
				/obj/item/clothing/head/security_beanie = 6,
				/obj/item/clothing/head/hats/caphat/parade/fedcap/sec = 6,
				/obj/item/clothing/head/cowboy/skyrat/cattleman/sec = 6,
				/obj/item/clothing/head/cowboy/skyrat/cattleman/wide/sec = 6,
				/obj/item/clothing/head/costume/ushanka/sec = 6,
				/obj/item/clothing/head/beret/sec/splurt = 6,
				/obj/item/clothing/head/security_garrison = 6,
				/obj/item/clothing/glasses/hud/security = 6,
				/obj/item/clothing/glasses/hud/security/prescription = 6,
				/obj/item/clothing/mask/bandana/striped/security = 6,
				/obj/item/clothing/mask/gas/sechailer = 6,
				/obj/item/clothing/neck/pauldron = 6,
				/obj/item/clothing/neck/security_cape = 6,
				/obj/item/clothing/neck/security_cape/armplate = 6,
				/obj/item/clothing/gloves/color/black = 6,
				/obj/item/clothing/gloves/color/black/security = 6,
				/obj/item/clothing/accessory/armband/deputy = 6,
				/obj/item/clothing/under/rank/security/officer/formal = 6,
				/obj/item/clothing/suit/jacket/officer/blue = 6,
				/obj/item/clothing/head/beret/sec/navyofficer = 6,
				/obj/item/clothing/under/rank/security/security_bunnysuit = 6,
				/obj/item/clothing/suit/armor/security_tailcoat = 6,
				/obj/item/clothing/neck/tie/bunnytie/security/tied = 6,
				/obj/item/clothing/head/playbunnyears/security = 6,
			)
		),
		list(
			"name" = "Viro",
			"icon" = "vest",
			"products" = list(
					/obj/item/clothing/under/rank/security/viro/officer = 6,
					/obj/item/clothing/under/rank/security/viro/officer/lowcut = 6,
					/obj/item/clothing/under/rank/security/viro/officer/skirt = 6,
					/obj/item/clothing/under/rank/security/viro/officer/formal = 6,
					/obj/item/clothing/under/rank/security/viro/officer/bodysuit = 6,
					/obj/item/clothing/suit/armor/vest/secwintercoat = 6,
					/obj/item/clothing/suit/armor/vest/viro = 6,
					/obj/item/clothing/suit/armor/vest/viro/heavy = 6,
					/obj/item/clothing/suit/armor/vest/viro/leatherjacket = 6,
					/obj/item/clothing/suit/armor/vest/viro/softshell = 6,
					/obj/item/clothing/head/sec/viro = 6,
					/obj/item/clothing/head/sec/viro/beanie = 6,
			),
		),
)
