/obj/item/storage/bag/garment/blueshield/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/rank/security/nanotrasen/hr(src)
	new /obj/item/clothing/suit/armor/vest(src)
	new /obj/item/clothing/head/helmet/swat/nanotrasen/hr(src)
	new /obj/item/clothing/shoes/combat(src)
	new /obj/item/clothing/mask/gas/sechailer/swat(src)
	new /obj/item/clothing/head/beret/nanotrasen_formal(src)
	new /obj/item/clothing/head/hats/warden/drill/nanotrasen/nt(src)
	new /obj/item/clothing/under/rank/nanotrasen/tactical(src)
	new /obj/item/clothing/under/rank/nanotrasen/tactical/skirt(src)
	new /obj/item/clothing/mask/gas/atmos/nanotrasen(src)
